### ISSUE TITLE
Track important tasks

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#143]
Package management:
- [ ] add straight as git submodule #98
- [ ] add use-package as git submodule #98

Project Layout:
- [ ] allow using lisp_fn macro in other crates than the main crate #65 
- [ ] Remove unused code from remacs-lib #23 

General improvements:
- [ ] Merge OSX improvements #99

**Comment by brotzeit** [comment]
I would add descriptions to the tasks and a short introduction(everybody is welcome to pick up a task etc.). If anybody wants to add something or has a better idea how we can do this, be my guest.

**Comment by DavidDeSimone** [comment]
I've added a few JavaScript related tasks. I plan on fleshing them out a little more over the weekend. 

For anyone grabbing a task related to JS, I am always on gitter and willing to chat if you have questions.
