### ISSUE TITLE
[Meta] Compatibility of packages, distributions

### ISSUE THREAD

**Issue by black7375** [emacs-ng/emacs-ng#197]
We can investigate compatibility with packages or distributions.

**Method**
It is investigated based on two.
- c961560317b5caaf19120e897a18b8c2fd08698a: before merge #185
- e1705229ca31ed450c5237573ba3f40c26207e07: merge

**Distributions**
- [ ] [Doom Emacs](https://github.com/hlissner/doom-emacs): #58
- [ ] [Spacemacs](https://github.com/syl20bnr/spacemacs)
- [ ] [Prelude](https://github.com/bbatsov/prelude)

**Packages**
Plan to list only incompatible packages.

**Comment by brotzeit** [comment]
I wonder if it's easy to stay up-to-date with the compatibility notes that we put in our docs. We already had the situation that doom-emacs used a native-comp feature that we hadn't merged at this point.

**Comment by black7375** [comment]
It's very easy to create upstream workflow.
How about creating a pull request once a month after automatically merging to `upstream` branch once a week?

**Comment by brotzeit** [comment]
Sure, we can try that.
