### ISSUE TITLE
Move code of main crate to other crates and put lib.rs to root of main crate

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#276]
We want to restructure our rust code base and move all code to crates/. This issue serves for tracking the restructuring process.

- [ ] #66 Move webrender related code to seperate crate 
- [x] #271 Move deno related code to seperate crate deno/javascript
- [x] #274 Move async code to seperate crate
- [x] #277 Add crate for ng_module.rs 
- [ ] update build.rs to stop generating include files except the main c_exports file
- [x] allow use of def_lisp_sym outside the main crate
